### PR TITLE
PAPILIO-34-profile-creation

### PR DESCRIPTION
**Pull request by p-carrier**
# General info

**Issue number**: Papilio-34

**Task description**: 
The task was to add the profile of the companies
- creation of the profile in business creation process
- Add profile page to dashboard
- Display profile in dashboard page
- Allow update of the different profile information

# Manual Testing
to test the profile creation you have to create your own business: 
1. start the backend
` npm run build && npm start`
2. start the website
`npm start`
3. on the main page add the businessId then click on create business
4. enter the profile information then click next
5. enter the admin root account information then click next
6. click submit
7. using postman visit the following url by entering the businessId you enter in 3 in place of `:businessId`
`http://localhost:1337/api/business/get/:businessId`

# Testing
To run all the unit test, run the following code: 
`npm test`

**Test coverage**:
Screen Shot 2022-11-02 at 8 54 15 PM
Screen Shot 2022-11-02 at 8 54 38 PM

## Notes
- There is no need to worry about the */*.stories.tsx files. They are not needed to make the overall project works.

### CODE REVIEW

**Review by DrakeHunterK7 — COMMENTED** [review]
There is an issue right now where the fields in the Profile page are not editable and nothing can be typed in. This should be fixed. Pretty solid UI design though.

**Comment by p-carrier** [comment]
@DrakeHunterK7 I made the changes and upload a new version where the value can be change

**Comment by DrakeHunterK7** [comment]
Perfect, I can edit now. But the "Create Business" button is not working, might need to look into it.

**Review by DrakeHunterK7 — APPROVED** [review]
The frontend works as expected! Great work, @p-carrier !

**Comment by mth-1012** [comment]
image

Postal Code is usually the last field or second to last before Country in a normal scenario.

**Comment by mth-1012** [comment]
I hope no one writes Wakanda as the Country lol. In all seriousness Country should be a drop down.

**Review by mth-1012 — APPROVED** [review]
👍

**Comment by p-carrier** [comment]
I have changed the order for the postal code.

**Pull request merged**
